# Generated by Django 4.0.6 on 2023-08-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='maximum_token',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='temperature',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
