# Generated by Django 4.0.6 on 2023-08-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_documents_maximum_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentsetting_text_setting',
            name='font_family',
        ),
        migrations.RemoveField(
            model_name='documentsetting_text_setting',
            name='font_size',
        ),
        migrations.RemoveField(
            model_name='documentsetting_text_setting',
            name='font_style',
        ),
        migrations.AddField(
            model_name='documentsetting_text_setting',
            name='h1',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentsetting_text_setting',
            name='h2',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentsetting_text_setting',
            name='h3',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentsetting_text_setting',
            name='h4',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentsetting_text_setting',
            name='h5',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentsetting_text_setting',
            name='normal',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentsetting_text_setting',
            name='title',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
