# Generated by Django 4.0.6 on 2023-08-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_documentsetting_text_setting_font_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsetting_text_setting',
            name='h6',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
