# Generated by Django 4.0.6 on 2023-08-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_documentsetting_text_setting_h6'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botrole',
            name='bot',
        ),
        migrations.AddField(
            model_name='botrole',
            name='company',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='botrole',
            name='designation',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='botrole',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='botrole',
            name='role',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
