# Generated by Django 4.0.6 on 2023-08-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_botrole_bot_botrole_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botrole',
            name='is_default',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
