# Generated by Django 4.0.6 on 2023-08-22 12:14

from django.db import migrations, models
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_fontfamilystyle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvite',
            name='contact',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='teaminvite',
            name='country_code',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='teaminvite',
            name='token',
            field=models.CharField(default=secrets.token_hex, max_length=300),
        ),
    ]
