# Generated by Django 4.0.6 on 2023-08-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_teaminvite_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
