# Generated by Django 4.0.6 on 2023-08-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_documents_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='status',
            field=models.CharField(blank=True, choices=[('in queue', 'in queue'), ('not in queue', 'not in queue'), ('message not found', 'message not found'), ('complete', 'complete'), ('failed', 'failed')], default='in queue', max_length=300, null=True),
        ),
    ]
